name: Java Workflow

on:
  push:
    paths:
      - 'workouts/java/**'
  pull_request:
    paths:
      - 'workouts/java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: ./workouts/java

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports
          path: ./workouts/java/build/reports/
