name: PHP Workflow

on:
  push:
  pull_request:

jobs:

  # see https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        id: set-env
        run: |
          echo "DOCKER_BUILD_REPOSITORY=jelovac/swe-workout-php" >> $GITHUB_ENV
          echo "BUILD_ID=W${{ github.run_id }}I${{ github.run_number }}" >> $GITHUB_ENV
          echo "DOCKER_BUILD_TAG=${{ env.DOCKER_BUILD_REPOSITORY }}:build_${{ env.BUILD_ID }}" >> $GITHUB_ENV
          echo "DOCKER_RELEASE_TAG=${{ env.DOCKER_BUILD_REPOSITORY }}:latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            --target package \
            --tag $DOCKER_BUILD_TAG \
            --label "build_id=${BUILD_ID}" \
            excercises/php

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push built Docker Image
        run: |
          docker push $DOCKER_BUILD_TAG

      - name: Release built Docker Image
        if: >
          github.ref == 'refs/heads/main' &&
          (
            github.event_name == 'push' ||
            (
              github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true
            )
          )
        run: |
          docker tag $DOCKER_BUILD_TAG $DOCKER_RELEASE_TAG
          docker push $DOCKER_RELEASE_TAG

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Perform PHPUnit tests
        container:
          image: "${{ env.DOCKER_BUILD_TAG }}"
        run: |
          composer run code:test -- --log-junit phpunit.report.xml
          echo "::set-output name=file-path::$(pwd)/phpunit.report.xml"

      - uses: actions/upload-artifact@v3
        with:
          name: phpunit-report
          path: phpunit.report.xml
