name: PHP Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      DOCKER_BUILD_REPOSITORY: ${{ steps.assign_env_vars.outputs.DOCKER_BUILD_REPOSITORY }}
      DOCKER_BUILD_TAG: ${{ steps.assign_env_vars.outputs.DOCKER_BUILD_TAG }}
      DOCKER_RELEASE_TAG: ${{ steps.assign_env_vars.outputs.DOCKER_RELEASE_TAG }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/set-build-id.yml

      - uses: ./.github/workflows/actions/set-docker-build-vars.yml

      - name: Build Docker Image
        run: |
          docker build \
            --target package \
            --tag $DOCKER_BUILD_TAG \
            --label "build_id=${BUILD_ID}" \
            excercises/php

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push built Docker Image
        run: |
          docker push $DOCKER_BUILD_TAG

      - name: Release built Docker Image
        if: >
          github.ref == 'refs/heads/main' &&
          (
            github.event_name == 'push' ||
            (
              github.event_name == 'pull_request' &&
              github.event.pull_request.merged == true
            )
          )
        run: |
          docker tag $DOCKER_BUILD_TAG $DOCKER_RELEASE_TAG
          docker push $DOCKER_RELEASE_TAG

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/set-build-id.yml

      - uses: ./.github/workflows/actions/set-docker-build-vars.yml

      - name: Perform PHPUnit tests
        run: |
          touch phpunit.report.xml
          docker run -v "$(pwd)/phpunit.report.xml:/var/www/app/phpunit.report.xml" "${DOCKER_BUILD_TAG}" bash -c "composer run code:test -- --log-junit phpunit.report.xml"
          echo "::set-output name=file-path::$(pwd)/phpunit.report.xml"

      - uses: actions/upload-artifact@v3
        with:
          name: phpunit-report
          path: phpunit.report.xml
